spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.163.com
    username: datapps@163.com
    password: datapps123456
    default-encoding: UTF-8
thymeleaf:
  template:
    path: D:\\Projects\\IdeaProjects\\spring-boot-learning\\spring-boot-mail\\src\\main\\resources\\templates\\
server:
  port: 8088