spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  output:
    ansi:
      enabled: always
  mail:
    host:
    username:
    password:
    default-encoding: UTF-8
thymeleaf:
  template:
    path: D:\\Projects\\IdeaProjects\\spring-boot-learning\\spring-boot-mail\\src\\main\\resources\\templates\\
server:
  port: 8088